### ISSUE TITLE
Suggestion: Would you consider docker?

### ISSUE THREAD

**Issue by TatisLois** [manikandanraji/AniX#1]
For ease of standup and using would you consider dockerizing it?

I’m willing to help if there’s interest!

**Comment by OliverBrotchie** [comment]
Docker would make this project so much easier!

**Comment by tortoricischwartzllp** [comment]
Hi Lois.
We have been trying to contact you.
Please contact us as soon as possible.
Thank you.

**Comment by luckykuno** [comment]
do I need to have my own scraper?

**Comment by manikandanraji** [comment]
both the frontend and backend is now dockerized.
