### ISSUE TITLE
how to install 

### ISSUE THREAD

**Issue by joellui** [manikandanraji/AniX#3]
can you pls give a step by step instruction in the GitHub document
the instruction you have provided is not enough

**Comment by joellui** [comment]
I don't see any python script for scrapping  what should I upload on Heroku

**Comment by hfomar-nafcs** [comment]
Not Sure, Have you Figured this Out Yet?

**Comment by manikandanraji** [comment]
Right now, I am moving away from using firebase and rewriting the scraper without depending on firebase SDK. I'll post the scraper source code once I finish the rewrite.

**Comment by hfomar-nafcs** [comment]
@manikandanraji  Thanks
